name: cdie

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required libs
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake -y

      - name: Build cdie
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j$(nproc)

      - name: Upload Linux Release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Beta
          draft: false
          prerelease: true
          files: build/src/console/cdie
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
